In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("50_Startups.csv")

In [3]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        108 non-null    float64
 1   Administration   108 non-null    float64
 2   Marketing Spend  108 non-null    float64
 3   State            108 non-null    object 
 4   Profit           108 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.3+ KB


In [5]:
data.isnull().any

<bound method NDFrame._add_numeric_operations.<locals>.any of      R&D Spend  Administration  Marketing Spend  State  Profit
0        False           False            False  False   False
1        False           False            False  False   False
2        False           False            False  False   False
3        False           False            False  False   False
4        False           False            False  False   False
..         ...             ...              ...    ...     ...
103      False           False            False  False   False
104      False           False            False  False   False
105      False           False            False  False   False
106      False           False            False  False   False
107      False           False            False  False   False

[108 rows x 5 columns]>

In [6]:
data["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le=LabelEncoder()
data["State"]=le.fit_transform(data["State"])

In [9]:
data.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [10]:
x= data.iloc[:,0:4].values
y= data.iloc[:,4:5].values

In [11]:
x.shape

(108, 4)

In [12]:
y.shape

(108, 1)

In [ ]:
#one hot encoder converts numerical continuos to categorical values

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
one= OneHotEncoder()

In [17]:
z= one.fit_transform(x[:,3:4]).toarray()

In [18]:
z

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [19]:
x= np.delete(x,3,axis=1)
x.shape

(108, 3)

In [20]:
x= np.concatenate((z,x),axis=1)
x.shape

(108, 6)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [23]:
x_train.shape
#80 % of 108

(86, 6)

In [24]:
x_test.shape

(22, 6)

In [ ]:
#model building using linear regressiuon

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
lr= LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
#find predicted value of y

In [27]:
ypred= lr.predict(x_test)
ypred

array([[ 48466.75433416],
       [134429.39628446],
       [ 76093.94745793],
       [181201.94746513],
       [113069.45110036],
       [134397.50337434],
       [128842.89457941],
       [159664.83856911],
       [116952.09718498],
       [ 46372.4777126 ],
       [102406.37641002],
       [115207.87076438],
       [ 48466.75433416],
       [119345.51846304],
       [ 88717.92542864],
       [127301.68084921],
       [127301.68084921],
       [ 91145.83032982],
       [ 58337.13774602],
       [146474.04747225],
       [149038.44713345],
       [152718.63782935]])

In [28]:
y_test

array([[ 64926.08],
       [146121.95],
       [ 90708.19],
       [191050.39],
       [108552.04],
       [144259.4 ],
       [124266.9 ],
       [155752.6 ],
       [126992.93],
       [ 42559.73],
       [101004.64],
       [110352.25],
       [ 64926.08],
       [111313.02],
       [ 89949.14],
       [134307.35],
       [134307.35],
       [ 96712.8 ],
       [ 49490.75],
       [129917.04],
       [132602.65],
       [152211.77]])

In [29]:
from sklearn.metrics import r2_score
#r2score is performance evaluation metric it helps to compare the model with the baseline 

In [30]:
acc= r2_score(ypred,y_test)
acc

0.9316315637551524

In [32]:
yp= lr.predict([[1,0,0,124,12345,1234567]])
yp

array([[92357.43497162]])